Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      # Red Hat Enterprise Linux 7.6 (HVM), SSD Volume Type
      ImageId: ami-011b3ccf1bd6db744
      KeyName: key1
      SecurityGroups:
        - !Ref InstanceSecurityGroup
      UserData: !Base64 |
        #!/bin/bash
        sudo su
        yum install git -y
        git clone https://github.com/abelhbeyene/cloudformation-experiment.git /usr/share/nginx/html

        curl https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm > /tmp/epel-release-latest-7.noarch.rpm
        yum install /tmp/epel-release-latest-7.noarch.rpm -y

        # Install docker: https://github.com/NaturalHistoryMuseum/scratchpads2/wiki/Install-Docker-and-Docker-Compose-(Centos-7)
        yum install -y yum-utils device-mapper-persistent-data lvm2
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.68-1.el7.noarch.rpm -y
        yum install docker-ce -y
        usermod -aG docker $(whoami)
        systemctl enable docker.service
        systemctl start docker.service

        # Install docker compose
        yum install -y python-pip
        pip install docker-compose
        yum upgrade python* -y

        # get docker-compose file and start container
        (cd /usr/share/nginx/html && docker-compose up --build -d)


  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH, HTTP, HTTPS security rules
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3000'
        ToPort: '3000'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0

Outputs:
  InstanceDNSName:
    Description: The DNSName of the Instance
    Value: !GetAtt Instance.PublicIp